scrape_configs:
  # MONGODB
  - job_name: Mongodb_exporter
    metrics_path: /metrics
    static_configs:
      - targets: ["mongodb_exporter:9216"]
        labels:
          hostname: mongodb_server
