name: Test app

on:
  workflow_call:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt
          pip install pytest

      - name: print ls -la
        run: |
          ls -la

      - name: Test with pytest
        run: |
          cd src
          pytest test.py
